logging:
  file: "log/main.log"
  level.org.springframework.kafka.listener: DEBUG
  level.org.springframework.kafka.listener.adapter: INFO
  level.org.apache.kafka.clients.NetworkClient: TRACE
  level.org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: DEBUG



spring:
  profiles.active: consumer
  #  profiles.active: offset-topic-reader

  kafka:
    bootstrap-servers: "some-host:9092"

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
      auto-commit-interval: 10000
      enable-auto-commit: true
